openapi: 3.0.3
info:
  title: Mock API for Orders
  description: This is a mock API for handling orders with basic validation and operations like GET, POST, and DELETE.
  version: 1.0.0
servers:
  - url: https://api.example.com/data
    description: Mock API server
paths:
  /:
    get:
      summary: Retrieve all orders or a specific order if query parameter <id> was used
      description: |
        Retrieve all orders or a specific order if an ID is provided in the query string.
      parameters:
        - name: id
          in: query
          description: The order ID to retrieve (optional).
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved all orders.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Order'
              example:
                OrderId1:
                  volume: 1
                  symbol: "EURUSD"
                  price: 1.23456
                  direction: "BUY"
                OrderId2:
                  volume: 10
                  symbol: "USDEUR"
                  price: 0.98765
                  direction: "SELL"
                OrderId3:
                  volume: 5
                  symbol: "JPYUSD"
                  price: 123.45001
                  direction: "BUY"
        '400':
          description: Bad request, the order ID must be an integer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Order not found or invalid URL.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new order
      description: |
        Create a new order by providing the order details as JSON in the request body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successfully created an order.
          content:
            application/json:
              schema:
                type: object
                properties:
                  OrderID:
                    type: integer
                    description: The ID of the created order.
        '400':
          description: Invalid order payload. Missing required fields or invalid values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found if the URL is incorrect.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{orderId}:
    delete:
      summary: Delete an order by ID
      description: |
        Delete an existing order by providing the order ID as a path parameter.
      parameters:
        - name: orderId
          in: path
          required: true
          description: The ID of the order to delete.
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted the order.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request. ID must be an integer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Order not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Order:
      type: object
      properties:
        volume:
          type: integer
          description: The volume of the order. Must be an integer greater than 0.
        symbol:
          type: string
          description: The currency pair for the order. Allowed symbols "EURUSD", "USDEUR", "JPYUSD".
        price:
          type: number
          format: float
          description: The price with 5 decimal points.
        direction:
          type: string
          enum:
            - BUY
            - SELL
          description: The order direction (BUY or SELL).

    Error:
      type: object
      properties:
        message:
          type: string
          description: The error message returned by the API.
